### ISSUE TITLE
Frontend: Design FormComponent

### ISSUE THREAD

**Issue by Romerico234** [Romerico234/Towson-Academic-Pathway#25]
# TAP Questionnaire

Our goal is to make scheduling courses as easy and efficient as possible. Please provide the following details:

---

## Personal Information
1. **Email**: (Displayed automatically, unchangeable)
2. **First Name**: (Selected automatically from your profile)
3. **Last Name**: (Selected automatically from your profile)
4. **Upload Transcript**: Upload your unofficial transcript.

---

### General Preferences
1. **Graduation Date**:  
   - ☐ Fall 2024  
   - ☐ Spring 2025  
   - ☐ Summer 2025  
   - ☐ Other (choose from dropdown)  
2. **Credit Hours Per Semester**:  
   - ☐ 12  
   - ☐ 15  
   - ☐ 18  
3. **Class Format**:  
   - ☐ Online  
   - ☐ In-person  
   - ☐ No preference  
4. **Class Times**:  
   - ☐ Morning  
   - ☐ Afternoon  
   - ☐ Evening  
   - ☐ No preference  
5. **Class Days**: (Select all that apply)  
   - ☐ Monday  
   - ☐ Tuesday  
   - ☐ Wednesday  
   - ☐ Thursday  
   - ☐ Friday  
6. **Summer/Winter Classes**:  
   - ☐ Yes  
   - ☐ No  

### Course and Degree Preferences
1. **Electives**:  
   - ☐ Include optional electives  
   - ☐ Focus only on required courses  

---

## Academic Progress
1. **General Education Requirements**:  
   - ☐ Completed  
   - ☐ Not completed  
2. **Prerequisites**:  
   - ☐ Completed all prerequisites  
   - ☐ Missing some prerequisites  
3. **Withdrawn Courses**:  
   - ☐ No withdrawn courses  
   - ☐ Some withdrawn courses (we will include these automatically in the plan)

---

## Course Scheduling
1. **Starting Semester**:  
   - ☐ Fall 2024  
   - ☐ Spring 2025  
   - ☐ Summer 2025  
2. **Required Courses for Next Semester**:  
   - ☐ No specific courses required  
   - ☐ Some courses required (we will recommend based on your transcript)  
3. **Busy Terms**:  
   - ☐ No specific terms unavailable  
   - ☐ Some terms unavailable (we will adjust accordingly)

---

## Dynamic Adjustments
1. **Unavailable Courses**:  
   - ☐ Substitute with an equivalent course  
   - ☐ Wait for the next available term  
2. **Prerequisite Handling**:  
   - ☐ Add missing prerequisites automatically  
   - ☐ Skip and show a warning in the plan  
3. **Preference Conflicts**:  
   - ☐ Prioritize timing  
   - ☐ Prioritize instructor  
   - ☐ No specific priority  

---

## Additional Comments  
(Free-response text field)

**Comment by DeLloydTimothy** [comment]
I think the question about prerequisites is unnecessary; TAP should be able to figure that out on its own.
