### ISSUE TITLE
Data: Add courses and majors for Fisher College 

### ISSUE THREAD

**Issue by Romerico234** [Romerico234/Towson-Academic-Pathway#76]
# Data Collection Instructions

## To Get Course Data
1. **Access the Towson University Catalog**: Navigate to the TU course catalog website.
2. **Select a Course**: Click on any course to view its details.
3. **Inspect the Network Tab**:
   - Open your browser's Developer Tools (usually accessible via `F12` or right-click > `Inspect`).
   - Navigate to the **Network** tab.
   - Look for requests labeled as **JSON** or **Fetch** when loading the course details.
4. **Identify the Relevant Data**:
   - Find the request containing the course data.
   - Download or copy the JSON payload.
5. **Transform the Data**:
   - Use ChatGPT or another tool to restructure the JSON data to match the schema in your application.
   - Use existing course data as a reference for the required schema.

Video:

https://github.com/user-attachments/assets/0446aaea-8c33-466c-8e68-9a9e6b3cdb87

---

## To Get Majors
1. **Reference the Towson University Undergraduate Catalog (PDF)**:
   - Use the [Undergraduate 24-25 Catalog PDF](https://catalog.towson.edu/pdf/Undergraduate%2024-25.pdf).
2. **Focus on Fisher College of Science Majors**:
   - Go through all the majors listed under the Fisher College of Science.
3. **Extract Data**:
   - Manually extract the information for each major 
4. **Format the Data**:
   - Ensure that the extracted data adheres to the same schema and format as your application's existing data.

---

## Double-Check the Schema
1. Compare the newly extracted and transformed data against the existing data in your application.
2. Verify that all fields align with your defined schema.
3. Make corrections if any discrepancies are found to maintain consistency.

**Comment by DeLloydTimothy** [comment]
I got this.
